- name: Configure NTP servers for an ESXi Host
  vmware_host_ntp:
    hostname: '{{ current_ip }}'
    username: '{{ esx.ansible_user }}'
    password: '{{ esx.ansible_password }}'
    esxi_hostname: '{{ current_ip }}'
    validate_certs: no
    ntp_servers: "{{ esx.ntp }}"
    state: present
  delegate_to: localhost

- name: Start ntpd setting for an ESXi Host with Service policy
  vmware_host_service_manager:
    hostname: '{{ current_ip }}'
    username: '{{ esx.ansible_user }}'
    password: '{{ esx.ansible_password }}'
    esxi_hostname: '{{ current_ip }}'
    validate_certs: no
    service_name: ntpd
    service_policy: on
    state: present
  delegate_to: localhost